// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBIL70FT9xoa2bAbuexT5_TVi11uAxkU',
    appId: '1:447069044010:web:acad53d06b8bcbbb343253',
    messagingSenderId: '447069044010',
    projectId: 'book-bridge-2026',
    authDomain: 'book-bridge-2026.firebaseapp.com',
    storageBucket: 'book-bridge-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeoEdEUm1-YQCl7NAi1S6PcUr1sfG5m24',
    appId: '1:447069044010:android:99ea345f10e2a8bb343253',
    messagingSenderId: '447069044010',
    projectId: 'book-bridge-2026',
    storageBucket: 'book-bridge-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzvjtGtAlS-75LBd17_5FA08dv7OtUmSg',
    appId: '1:447069044010:ios:bfb22a4f5a3ec0e5343253',
    messagingSenderId: '447069044010',
    projectId: 'book-bridge-2026',
    storageBucket: 'book-bridge-2026.firebasestorage.app',
    iosBundleId: 'com.bookbridge.app',
  );
}
