// File generated by FlutterFire CLI.
// This is a stub - run `flutterfire configure` to generate actual options.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // TODO: Replace with actual Firebase project values from `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:web:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'book-bridge-app',
    authDomain: 'book-bridge-app.firebaseapp.com',
    storageBucket: 'book-bridge-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:android:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'book-bridge-app',
    storageBucket: 'book-bridge-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:ios:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'book-bridge-app',
    storageBucket: 'book-bridge-app.appspot.com',
    iosBundleId: 'com.bookbridge.app',
  );
}
